---
title: "Reproducible documents"
author: "Jessica Preston"
format: html
---

#Quarto document is a bit like the final product

```{r setup}
library(targets)
library(tidyverse)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Makgina a table

```{r}
lipidomics |>
  group_by(metabolite) |>
  summarize(across(value, list(mean = mean, sd = sd))) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 1))) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, "Mean SD" = MeanSD)
```

```{r}
create_table_descriptive_stats <- function(data) {
  data |>
    group_by(metabolite) |>
    summarize(across(value, list(mean = mean, sd = sd))) |>
    mutate(across(where(is.numeric), \(x) round(x, digits = 1))) |>
    mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
    select(Metabolite = metabolite, "Mean SD" = MeanSD)
}

# Use it like this, which should give the same output as before.
create_table_descriptive_stats(lipidomics)
```
